# Generated by Django 3.2.8 on 2021-10-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientmanager', '0002_client_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(default='pending', max_length=64),
        ),
    ]
